CREATE TABLE IF NOT EXISTS test_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT(20) UNSIGNED NOT NULL,
    assignment_id BIGINT(20) UNSIGNED NOT NULL,
    test_id BIGINT(20) UNSIGNED NOT NULL,
    student_id BIGINT(20) UNSIGNED NOT NULL,
    question_id BIGINT(20) UNSIGNED NULL,
    action ENUM(
        'test_start',
        'test_resume',
        'test_submit',
        'question_show',
        'question_answer',
        'question_change_answer',
        'navigate_next',
        'navigate_prev',
        'tab_hidden',
        'tab_visible',
        'fullscreen_enter',
        'fullscreen_exit',
        'page_reload',
        'timeout',
        'forced_finish',
        'suspicious_pattern'
    ) NOT NULL,
    ip VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(255) DEFAULT NULL,
    meta JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_logs_attempt (attempt_id),
    KEY idx_logs_assignment (assignment_id),
    KEY idx_logs_student (student_id),
    KEY idx_logs_action (action),
    CONSTRAINT fk_logs_attempt FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
    CONSTRAINT fk_logs_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
